feature test warehouse - service.
LucasTI79/meli_bootcamp_go_w2-4 pull request #21
Opened 2023-06-22 18:04 UTC by ThamyrisCabralArraes

100% coverage in the service.

2023-06-22 19:25 UTC, victorvernalha requested changes
Excelente! Gostei bastante dos testes, parabéns :)

O único comentário que faço é pra que mande um commit deletando o arquivo de cobertura de código, o resto já está aprovadíssimo

2023-06-22 19:25 UTC, victorvernalha commented on internal/warehouse/coverage.out
Gostaria de pedir para que o arquivo de cobertura de código fosse apagado, por favor :)

2023-06-22 19:40 UTC, ThamyrisCabralArraes commented on internal/warehouse/coverage.out
Excluido!!! Obgg!

2023-06-23 18:09 UTC, biancascclaro approved these changes

2023-06-23 18:55 UTC, victorvernalha approved these changes

2023-06-23 18:56 UTC, merged